services:
  between-us:
    build: .
    container_name: between-us
    restart: unless-stopped

    volumes:
      - ./instance:/app/instance

    environment:
      - FLASK_ENV=production

    labels:
      - "traefik.enable=true"

      # HTTP
      - "traefik.http.routers.between-us.rule=Host(`app.betweenus.fyi`)"
      - "traefik.http.routers.between-us.entrypoints=web"

      # HTTPS
      - "traefik.http.routers.between-us-secure.rule=Host(`app.betweenus.fyi`)"
      - "traefik.http.routers.between-us-secure.entrypoints=web"
     # - "traefik.http.routers.between-us-secure.tls=true"
     # - "traefik.http.routers.between-us-secure.tls.certresolver=letsencrypt"

      # Service
      - "traefik.http.services.between-us.loadbalancer.server.port=5000"

    networks:
      - traefik-net

networks:
  traefik-net:
    external: true